# Generated by Django 3.1.8 on 2021-05-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_content'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('flexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex.flexpage')),
            ],
            options={
                'verbose_name': 'Project Index Page',
                'verbose_name_plural': 'Project Index Pages',
            },
            bases=('flex.flexpage',),
        ),
    ]
