version: '3.7'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8009
    # volumes:
      # - ./static:/home/app/web/static
      # - ./media:/home/app/web/media
    ports:
      - 8009:8009
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13.3-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data_prod: