# Generated by Django 3.1.8 on 2021-05-19 16:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_hero_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='skills_and_tools',
            field=wagtail.core.fields.StreamField([('skills_and_tools', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_title='Add a title', required=False)), ('skills', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=100, required=False))])))]))], blank=True),
        ),
    ]
