# Generated by Django 3.1.8 on 2021-05-07 20:34

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock(form_classname='richtext'))], blank=True, null=True),
        ),
    ]
