# Generated by Django 3.1.8 on 2021-05-08 12:26

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock(form_classname='richtext')), ('features_and_tools', wagtail.core.blocks.StructBlock([('features', wagtail.core.blocks.RichTextBlock(help_text='List the features', required=False)), ('tools', wagtail.core.blocks.RichTextBlock(help_text='List the tools', required=False))], classname='featuresandtools'))], blank=True, null=True),
        ),
    ]
