# Generated by Django 3.1.8 on 2021-05-19 16:04

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_auto_20210508_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock(form_classname='richtext')), ('features_and_tools', wagtail.core.blocks.StructBlock([('features', wagtail.core.blocks.RichTextBlock(help_text='List the features', required=False)), ('tools', wagtail.core.blocks.RichTextBlock(help_text='List the tools', required=False))], classname='featuresandtools')), ('codeblock', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], default_language='python', label='Code Block'))], blank=True, null=True),
        ),
    ]
